# Generated by Django 2.1.1 on 2018-09-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CUSTOMER',
            fields=[
                ('CustomerId', models.AutoField(db_column='CustomerId', primary_key=True, serialize=False)),
                ('Address', models.CharField(blank=True, db_column='Address', max_length=200, null=True)),
                ('City', models.CharField(blank=True, db_column='City', max_length=50, null=True)),
                ('PostalCode', models.CharField(blank=True, db_column='PostalCode', max_length=50, null=True)),
                ('Country', models.CharField(blank=True, db_column='Country', max_length=50, null=True)),
                ('TelephoneNo', models.CharField(blank=True, db_column='TelephoneNo', max_length=50, null=True)),
                ('IsDeleted', models.CharField(blank=True, db_column='IsDeleted', max_length=50, null=True)),
                ('CREAT_TS', models.DateTimeField(blank=True, db_column='CREAT_TS', null=True)),
                ('UPD_TS', models.DateTimeField(blank=True, db_column='UPD_TS', null=True)),
            ],
            options={
                'db_table': 'CUSTOMER',
                'managed': True,
            },
        ),
    ]
