# Generated by Django 2.1.1 on 2018-09-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='CustomerName',
            field=models.CharField(blank=True, db_column='CustomerName', max_length=100, null=True),
        ),
    ]
